name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3.1.4

  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i, build and test
        run: |
          cd ClientApp
          npm i
          npm test
